# -*- coding: utf-8 -*-
"""predictive_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szZcTs-sx3OSVKoBXBq8lOeu3eItaPbF
"""

import pandas as pd
import numpy as np

data = pd.read_csv('/content/102203121-data.csv')
data.head()

names = data.iloc[:, 0]
values = data.iloc[:, 1:].values

norm_values = np.linalg.norm(values, axis=0)
norm_matrix = values / norm_values

weights = np.ones(norm_matrix.shape[1])
weighted_matrix = norm_matrix * weights

ideal_solution = np.max(weighted_matrix, axis=0)
negative_ideal_solution = np.min(weighted_matrix, axis=0)

dist_to_ideal = np.sqrt(np.sum((weighted_matrix - ideal_solution) ** 2, axis=1))
dist_to_negative_ideal = np.sqrt(np.sum((weighted_matrix - negative_ideal_solution) ** 2, axis=1))

topsis_scores = dist_to_negative_ideal / (dist_to_ideal + dist_to_negative_ideal)
ranks = np.argsort(topsis_scores)[::-1] + 1
data['Topsis Score'] = topsis_scores
data['Rank'] = ranks
data.to_csv('102203121-output.csv', index=False)

output=pd.read_csv('/content/102203121-output.csv')
output.head()